### ISSUE TITLE
Same requests are sent multiple time if previous one not resolved

### ISSUE THREAD

**Issue by chloeleichen** [atlassian-labs/react-resource-router#104]
See an example with jira-dashboard
https://user-images.githubusercontent.com/7508939/140255451-a957acab-0693-40ec-9de5-42cccd8f3a3e.mov

**Comment by jackbrown** [comment]
Thanks @chloeleichen for the report. I can replicate the issue in this sandbox https://codesandbox.io/s/rrr-replicating-issue-104-lqm0m?file=/src/about/index.tsx

**Comment by albertogasparin** [comment]
Fixed by #115 and release in `v0.19.0`
