### ISSUE TITLE
Do not expose a data key until loading has finished and there is no error to make more restful.

### ISSUE THREAD

**Issue by slevens-atlas** [atlassian-labs/react-resource-router#112]
The current implementation of `RouteResourceResponseBase` includes a `data` key which will always be `null` as defined in https://github.com/atlassian-labs/react-resource-router/blob/a4e0f0358c9987f5b0398ac76deaf491a96ce308/src/controllers/resource-store/constants.ts#L8

I suggest we remove the key entirely and let it only be set by the response successfully returning data. 

This will have the flow on effect of improving the typescript checking and will force developers to check `loading` and `error` before the `data` key will even appear.

Like this: 
```
export const Home = () => {
  const homeResponse = useResource(homeResource);

  if (homeResponse.error) {
    return <Error error={home.error} />;
  }

  if (homeResponse.loading) {
    return <Loading />;
  }
 
  // before this there is no data key on homeResponse
  return <div>{homeResponse.data.home.content}</div>;
};
```

**Comment by slevens-atlas** [comment]
I have a branch with the changes ready if someone can give me contributor access I can open a PR and attach to review.

**Comment by theKashey** [comment]
You are missing the "stale while invalidate" model, when you can have old `data` while `loading` a new one.

**Comment by slevens-atlas** [comment]
This makes a lot of sense, maybe we could include a state key and expose keys based on that? Could potentially be too rigid though. Otherwise if we are happy with the current implementation I can close this issue.

**Comment by slevens-atlas** [comment]
I'm going to close this issue. I think it is fine in its current state and leave it up to the dev to determine how they want to handle it
