### ISSUE TITLE
TypeScript@3 peer dependency?

### ISSUE THREAD

**Issue by marionebl** [atlassian-labs/react-resource-router#114]
Receiving a peer dependency warning for react-resource-router

```
➤ YN0060: │ @atlassian/canvas@workspace:. provides typescript (p87734) with version 4.5.5, which doesn't satisfy what react-resource-router requests
```

I don't see why it would depend on an explicit TypeScript major, could the peer dependency be removed or widened?

**Comment by albertogasparin** [comment]
That is a very good point. To be honest dunno why TS and Tslib are marked as dependencies. We publish transpiled bundles with type defs, so they should not be required at all.
Do you feel like raising PR to address that?

**Comment by marionebl** [comment]
https://github.com/atlassian-labs/react-resource-router/pull/117
