### ISSUE TITLE
Doesn't not work with React 18 StrictModel

### ISSUE THREAD

**Issue by liamqma** [atlassian-labs/react-resource-router#222]
To Reproduce the problem:

1. Go to https://github.com/atlassian-labs/react-resource-router/blob/master/examples/basic-routing/index.tsx#L45
2. Enable Strict Mode

```
const root = ReactDOM.createRoot(
  document.getElementById('root')
);

root.render(
  <React.StrictMode>
      <App />
  </React.StrictMode>
);
```
3. Then run `npm start`
4. Go `http://localhost:8080/basic-routing/`

Clicking on the link doesn't trigger the page change.

**Comment by ebergama** [comment]
There were some changes introduced with React 18 to the strict mode
- https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-strict-mode
- https://nx.dev/recipes/react/react-18#changes-to-strict-mode

Also, some interesting threads
- https://github.com/reactwg/react-18/discussions/19
- https://github.com/reactwg/react-18/discussions/18


Lastly, not sure if related, but react-router v5 does not work with R18 

https://github.com/facebook/react/issues/24451
