### ISSUE TITLE
Did you ever try with redux ?

### ISSUE THREAD

**Issue by castroCrea** [atlassian-labs/react-resource-router#39]
Hello,
I found your library trying to improve perf on react-router. So first nice move and good job 👍

Did you try your lib with redux & redux saga ?

I want to give a try
Thanks you

**Comment by albertogasparin** [comment]
Thanks! There is no limitations on the state implementation that you can use. In Redux case you can either use `useResource` hooks to pass the data into the store (we do that as we have multiple redux stores), or you can even pass the store as value in `Router` `resourceContext` prop https://atlassian-labs.github.io/react-resource-router/#/router/configuration?id=resourcecontext and then dispatch actions directly from the resource `getData` function.
It's up to you whenever you want to leverage the built-in resources caching layer or if you prefer use the resources to just trigger requests early.
